In [1]:
#--------------------------------------------------------------------------------------------#
#
# Code: CC01_CCAR_A03_data_manipulation_01.ipynb
#
# Objective: Step 1: Uploaded simulated data set for CCAR modeling / basereg CSV file
#            Step 2: Combine two types of files together
#
#
#            Jingru Chen
#            2026-03-18
#
#------------------------------------------------------------------------------------------#

# Step 1: Upload libraries

In [2]:
import numpy as np
import pandas as pd
from datetime import datetime, timedelta

In [3]:
from datetime import datetime
from zoneinfo import ZoneInfo

start = datetime.now( ZoneInfo("America/New_York"))

print( start.strftime("%Y-%m-%d %H:%M:%S %Z"))     # 2026-03-17 17:34:58 EDT
print( start.strftime("%Y-%m-%d %I:%M:%S %p %Z"))  # 2026-03-17 05:34:58 PM EDT

2026-03-19 20:08:18 EDT
2026-03-19 08:08:18 PM EDT

In [4]:
myout= "/content/sample_data"

In [5]:
pwd

'/content'

In [6]:
cd /content/sample_data/

/content/sample_data

#### CCAR_simulated_data_20260318_01.csv

In [7]:
ls -lta

total 163104
-rw-r--r-- 1 root root 51434417 Mar 20 00:07 CCAR_Mortgage_data_for_model_DEV_20260319_01.csv
drwxr-xr-x 1 root root     4096 Mar 20 00:07 ./
-rw-r--r-- 1 root root 58664555 Mar 19 23:45 CCAR_simulated_data_20260318_01.csv
-rw-r--r-- 1 root root    65427 Mar 19 23:45 basereg.csv
-rw-r--r-- 1 root root 18289443 Mar 17 17:58 mnist_test.csv
-rw-r--r-- 1 root root 36523880 Mar 17 17:58 mnist_train_small.csv
drwxr-xr-x 1 root root     4096 Mar 17 17:58 ../
-rw-r--r-- 1 root root   301141 Mar 17 17:58 california_housing_test.csv
-rw-r--r-- 1 root root  1706430 Mar 17 17:58 california_housing_train.csv
-rwxr-xr-x 1 root root     1697 Jan  1  2000 anscombe.json*
-rwxr-xr-x 1 root root      962 Jan  1  2000 README.md*

# Step 2: Upload two types of CSV files

In [8]:
my_2_col = ['mon', 'yr']

### Step 2-A: Upload simulated CCAR file

In [9]:
df_simu= pd.read_csv( myout + "/CCAR_simulated_data_20260318_01.csv" )

df_simu= df_simu.drop( columns= ['Unnamed: 0'])

df_simu[['yr', 'mon', 'day']] = df_simu['report_date'].str.split('-', expand=True)
df_simu['yrmo'] = df_simu['yr'] + df_simu['mon']
df_simu['report_yrmo'] = df_simu['yrmo']

for i in my_2_col:
    print( "---------2-A-1 Freq Table of {}".format(i), df_simu[i].value_counts() )

df_simu= df_simu.drop( columns = ['mon', 'yr' , 'day'])

print( "\n---------2-A-3 Freq Table of yrmo", df_simu.yrmo.value_counts() )

print( "\n---------2-A-3 Freq Table of product_type", df_simu.product_type.value_counts() )

df_simu[['_yr', '_mon', '_day']] = df_simu['default_date'].str.split('-', expand=True)
df_simu['default_yrmo'] = df_simu['_yr'] + df_simu['_mon']

df_simu['flag_default'] = 0
df_simu.loc[ df_simu['default_yrmo'] <= df_simu['report_yrmo'], 'flag_default' ] = 1

df_simu = df_simu.drop(columns= ['_yr', '_mon', '_day' ] )

print( "\n---------2-A-4 Freq Table of flag_default", df_simu.flag_default.value_counts() )

print( "\n---------2-A-5 Freq Table of default_yrmo", df_simu.product_type.value_counts() )

df_simu.info()

---------2-A-1 Freq Table of mon mon
01    25000
02    20000
03    20000
04    20000
05    20000
06    20000
07    20000
08    20000
09    20000
10    20000
11    20000
12    20000
Name: count, dtype: int64
---------2-A-1 Freq Table of yr yr
2014    60000
2015    60000
2016    60000
2017    60000
2018     5000
Name: count, dtype: int64

---------2-A-3 Freq Table of yrmo yrmo
201401    5000
201402    5000
201403    5000
201404    5000
201405    5000
201406    5000
201407    5000
201408    5000
201409    5000
201410    5000
201411    5000
201412    5000
201501    5000
201502    5000
201503    5000
201504    5000
201505    5000
201506    5000
201507    5000
201508    5000
201509    5000
201510    5000
201511    5000
201512    5000
201601    5000
201602    5000
201603    5000
201604    5000
201605    5000
201606    5000
201607    5000
201608    5000
201609    5000
201610    5000
201611    5000
201612    5000
201701    5000
201702    5000
201703    5000
201704    5000
201705    5000
201706    5000
201707    5000
201708    5000
201709    5000
201710    5000
201711    5000
201712    5000
201801    5000
Name: count, dtype: int64

---------2-A-3 Freq Table of product_type product_type
Mortgage    96579
Auto        62867
Card        62720
HELOC       22834
Name: count, dtype: int64

---------2-A-4 Freq Table of flag_default flag_default
0    137179
1    107821
Name: count, dtype: int64

---------2-A-5 Freq Table of default_yrmo product_type
Mortgage    96579
Auto        62867
Card        62720
HELOC       22834
Name: count, dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 245000 entries, 0 to 244999
Data columns (total 27 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   loan_id             245000 non-null  int64
 1   origination_date    245000 non-null  object
 2   report_date         245000 non-null  object
 3   num_payments        245000 non-null  int64
 4   original_balance    245000 non-null  float64
 5   current_balance_bk  245000 non-null  float64
 6   EAD                 245000 non-null  float64
 7   credit_score_orig   245000 non-null  float64
 8   loan_to_value_orig  245000 non-null  float64
 9   interest_rate       245000 non-null  float64
 10  product_type        245000 non-null  object
 11  ever_defaulted      245000 non-null  bool
 12  default_date        171157 non-null  object
 13  PD                  245000 non-null  float64
 14  LGD                 245000 non-null  float64
 15  projected_loss      245000 non-null  float64
 16  loan_term_months    245000 non-null  int64
 17  unemployment        245000 non-null  float64
 18  gdp_growth_qoq      245000 non-null  float64
 19  hpi_change          245000 non-null  float64
 20  bbb_spread          245000 non-null  float64
 21  months_elapsed      245000 non-null  int64
 22  current_balance     245000 non-null  float64
 23  yrmo                245000 non-null  object
 24  report_yrmo         245000 non-null  object
 25  default_yrmo        171157 non-null  object
 26  flag_default        245000 non-null  int64
dtypes: bool(1), float64(14), int64(5), object(7)
memory usage: 48.8+ MB

In [10]:
print( "\n---------2-A-4 Freq Table of flag_default", df_simu.flag_default.value_counts() )

---------2-A-4 Freq Table of flag_default flag_default
0    137179
1    107821
Name: count, dtype: int64

In [11]:
df_simu.loc[df_simu['loan_id'] == 1]

,loan_id,origination_date,report_date,num_payments,original_balance,current_balance_bk,EAD,credit_score_orig,loan_to_value_orig,interest_rate,...,unemployment,gdp_growth_qoq,hpi_change,bbb_spread,months_elapsed,current_balance,yrmo,report_yrmo,default_yrmo,flag_default
0,1,2012-03-31,2014-01-31,22,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,4.191571,0.000000,0.017034,1.237389,22,521464.12,201401,201401,201407,0
1,1,2012-03-31,2014-02-28,23,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,3.713178,-0.220578,0.340586,1.549005,23,520507.64,201402,201402,201407,0
2,1,2012-03-31,2014-03-31,24,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,4.782095,-2.366107,0.444276,1.268521,24,519548.63,201403,201403,201407,0
3,1,2012-03-31,2014-04-30,25,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,5.189047,2.633310,-0.915421,2.296397,25,518587.08,201404,201404,201407,0
4,1,2012-03-31,2014-05-31,26,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,4.904631,-0.405726,0.749689,2.411752,26,517622.99,201405,201405,201407,0
5,1,2012-03-31,2014-06-30,27,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,5.246438,-0.984923,-1.056674,2.991962,27,516656.35,201406,201406,201407,0
6,1,2012-03-31,2014-07-31,28,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,3.717565,-2.291407,-6.024290,2.322780,28,515687.16,201407,201407,201407,1
7,1,2012-03-31,2014-08-31,29,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,5.883795,0.448327,-9.525102,3.198286,29,514715.40,201408,201408,201407,1
8,1,2012-03-31,2014-09-30,30,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,5.041596,-3.381496,-10.500438,3.058415,30,513741.07,201409,201409,201407,1
9,1,2012-03-31,2014-10-31,31,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,6.161137,-0.631611,-11.797755,4.250539,31,512764.16,201410,201410,201407,1
10,1,2012-03-31,2014-11-30,32,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,6.046827,-1.983953,-13.402302,3.883603,32,511784.67,201411,201411,201407,1
11,1,2012-03-31,2014-12-31,33,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,5.798553,-0.982327,-13.976996,3.886961,33,510802.59,201412,201412,201407,1
12,1,2012-03-31,2015-01-31,34,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,5.487786,-0.324708,-12.976354,3.601410,34,509817.91,201501,201501,201407,1
13,1,2012-03-31,2015-02-28,35,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,5.823712,-3.262192,-13.095312,2.671798,35,508830.62,201502,201502,201407,1
14,1,2012-03-31,2015-03-31,36,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,5.131824,-4.207678,-12.922486,3.492343,36,507840.73,201503,201503,201407,1
15,1,2012-03-31,2015-04-30,37,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,6.403570,-2.876975,-15.342168,4.773533,37,506848.21,201504,201504,201407,1
16,1,2012-03-31,2015-05-31,38,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,5.144665,0.382635,-16.921341,3.837506,38,505853.08,201505,201505,201407,1
17,1,2012-03-31,2015-06-30,39,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,6.182608,-0.528360,-16.670808,3.148600,39,504855.30,201506,201506,201407,1
18,1,2012-03-31,2015-07-31,40,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,7.054795,-1.925222,-17.308790,3.951582,40,503854.89,201507,201507,201407,1
19,1,2012-03-31,2015-08-31,41,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,6.861207,2.342665,-17.393196,3.264570,41,502851.84,201508,201508,201407,1
20,1,2012-03-31,2015-09-30,42,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,6.096367,1.113177,-17.272611,3.452950,42,501846.13,201509,201509,201407,1
21,1,2012-03-31,2015-10-31,43,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,6.307628,0.678232,-17.823326,4.322740,43,500837.76,201510,201510,201407,1
22,1,2012-03-31,2015-11-30,44,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,6.740192,-2.503570,-16.250466,4.627061,44,499826.72,201511,201511,201407,1
23,1,2012-03-31,2015-12-31,45,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,7.145934,0.658226,-17.847770,3.812913,45,498813.01,201512,201512,201407,1
24,1,2012-03-31,2016-01-31,46,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,7.600620,-0.586725,-19.876408,4.064266,46,497796.62,201601,201601,201407,1
25,1,2012-03-31,2016-02-29,47,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,7.627072,-2.500077,-23.323861,3.652508,47,496777.54,201602,201602,201407,1
26,1,2012-03-31,2016-03-31,48,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,7.097332,-1.387381,-23.000956,4.539090,48,495755.77,201603,201603,201407,1
27,1,2012-03-31,2016-04-30,49,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,7.903743,-3.069182,-24.656037,3.557384,49,494731.29,201604,201604,201407,1
28,1,2012-03-31,2016-05-31,50,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,8.081801,-2.484272,-23.557029,4.653846,50,493704.10,201605,201605,201407,1
29,1,2012-03-31,2016-06-30,51,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,8.122491,-3.259516,-23.985100,4.989413,51,492674.19,201606,201606,201407,1
30,1,2012-03-31,2016-07-31,52,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,9.053774,0.521797,-25.293349,3.996526,52,491641.57,201607,201607,201407,1
31,1,2012-03-31,2016-08-31,53,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,8.488444,-1.327666,-27.675306,4.553979,53,490606.20,201608,201608,201407,1
32,1,2012-03-31,2016-09-30,54,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,8.720463,-2.894878,-27.205539,5.230612,54,489568.11,201609,201609,201407,1
33,1,2012-03-31,2016-10-31,55,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,9.219093,-0.268726,-28.086370,5.257054,55,488527.26,201610,201610,201407,1
34,1,2012-03-31,2016-11-30,56,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,8.944214,-1.197294,-28.484666,5.393116,56,487483.66,201611,201611,201407,1
35,1,2012-03-31,2016-12-31,57,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,8.519161,0.690910,-28.378004,5.764474,57,486437.31,201612,201612,201407,1
36,1,2012-03-31,2017-01-31,58,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,9.372081,-0.959994,-28.779375,4.696990,58,485388.18,201701,201701,201407,1
37,1,2012-03-31,2017-02-28,59,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,8.849859,-3.786938,-30.854102,6.233529,59,484336.28,201702,201702,201407,1
38,1,2012-03-31,2017-03-31,60,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,8.752790,-2.094139,-30.872200,5.725430,60,483281.60,201703,201703,201407,1
39,1,2012-03-31,2017-04-30,61,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,8.922459,-3.282951,-30.441899,5.667282,61,482224.12,201704,201704,201407,1
40,1,2012-03-31,2017-05-31,62,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,9.909206,-0.186586,-30.701556,5.014420,62,481163.86,201705,201705,201407,1
41,1,2012-03-31,2017-06-30,63,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,9.800182,0.752030,-30.553033,6.081120,63,480100.78,201706,201706,201407,1
42,1,2012-03-31,2017-07-31,64,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,10.111834,-3.979166,-30.264717,6.657218,64,479034.90,201707,201707,201407,1
43,1,2012-03-31,2017-08-31,65,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,10.072953,-1.424093,-31.658811,6.543277,65,477966.19,201708,201708,201407,1
44,1,2012-03-31,2017-09-30,66,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,10.033872,0.874952,-33.109147,6.669154,66,476894.66,201709,201709,201407,1
45,1,2012-03-31,2017-10-31,67,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,10.220955,-4.006385,-30.568966,6.471574,68,474743.09,201710,201710,201407,1
46,1,2012-03-31,2017-11-30,68,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,10.465598,-1.983028,-29.380326,6.747004,69,473663.03,201711,201711,201407,1
47,1,2012-03-31,2017-12-31,69,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,10.123587,-1.200413,-30.252635,6.227190,70,472580.12,201712,201712,201407,1
48,1,2012-03-31,2018-01-31,70,541879.93,430203.61,430203.61,731.0,81.022504,3.174,...,9.983880,0.721398,-30.028392,6.997140,71,471494.34,201801,201801,201407,1

In [12]:
df_simu.loc[df_simu['loan_id'] == 1][['loan_id',	'origination_date', 'report_date',	'num_payments', 'default_date' ]]

    loan_id origination_date report_date  num_payments default_date
0         1       2012-03-31  2014-01-31            22   2014-07-31
1         1       2012-03-31  2014-02-28            23   2014-07-31
2         1       2012-03-31  2014-03-31            24   2014-07-31
3         1       2012-03-31  2014-04-30            25   2014-07-31
4         1       2012-03-31  2014-05-31            26   2014-07-31
5         1       2012-03-31  2014-06-30            27   2014-07-31
6         1       2012-03-31  2014-07-31            28   2014-07-31
7         1       2012-03-31  2014-08-31            29   2014-07-31
8         1       2012-03-31  2014-09-30            30   2014-07-31
9         1       2012-03-31  2014-10-31            31   2014-07-31
10        1       2012-03-31  2014-11-30            32   2014-07-31
11        1       2012-03-31  2014-12-31            33   2014-07-31
12        1       2012-03-31  2015-01-31            34   2014-07-31
13        1       2012-03-31  2015-02-28            35   2014-07-31
14        1       2012-03-31  2015-03-31            36   2014-07-31
15        1       2012-03-31  2015-04-30            37   2014-07-31
16        1       2012-03-31  2015-05-31            38   2014-07-31
17        1       2012-03-31  2015-06-30            39   2014-07-31
18        1       2012-03-31  2015-07-31            40   2014-07-31
19        1       2012-03-31  2015-08-31            41   2014-07-31
20        1       2012-03-31  2015-09-30            42   2014-07-31
21        1       2012-03-31  2015-10-31            43   2014-07-31
22        1       2012-03-31  2015-11-30            44   2014-07-31
23        1       2012-03-31  2015-12-31            45   2014-07-31
24        1       2012-03-31  2016-01-31            46   2014-07-31
25        1       2012-03-31  2016-02-29            47   2014-07-31
26        1       2012-03-31  2016-03-31            48   2014-07-31
27        1       2012-03-31  2016-04-30            49   2014-07-31
28        1       2012-03-31  2016-05-31            50   2014-07-31
29        1       2012-03-31  2016-06-30            51   2014-07-31
30        1       2012-03-31  2016-07-31            52   2014-07-31
31        1       2012-03-31  2016-08-31            53   2014-07-31
32        1       2012-03-31  2016-09-30            54   2014-07-31
33        1       2012-03-31  2016-10-31            55   2014-07-31
34        1       2012-03-31  2016-11-30            56   2014-07-31
35        1       2012-03-31  2016-12-31            57   2014-07-31
36        1       2012-03-31  2017-01-31            58   2014-07-31
37        1       2012-03-31  2017-02-28            59   2014-07-31
38        1       2012-03-31  2017-03-31            60   2014-07-31
39        1       2012-03-31  2017-04-30            61   2014-07-31
40        1       2012-03-31  2017-05-31            62   2014-07-31
41        1       2012-03-31  2017-06-30            63   2014-07-31
42        1       2012-03-31  2017-07-31            64   2014-07-31
43        1       2012-03-31  2017-08-31            65   2014-07-31
44        1       2012-03-31  2017-09-30            66   2014-07-31
45        1       2012-03-31  2017-10-31            67   2014-07-31
46        1       2012-03-31  2017-11-30            68   2014-07-31
47        1       2012-03-31  2017-12-31            69   2014-07-31
48        1       2012-03-31  2018-01-31            70   2014-07-31

### 2-B: Upload CCAR Base scenario file

In [13]:
month_dic= {'Jan' : '01', 'Feb' : '02', 'Mar' : '03',  'Apr' : '04', 'May' : '05', 'Jun' : '06',
         'Jul' : '07', 'Aug' : '08', 'Sep' : '09',  'Oct' : '10', 'Nov' : '11', 'Dec' : '12' }

for item, key in month_dic.items():
  print( item, key )

Jan 01
Feb 02
Mar 03
Apr 04
May 05
Jun 06
Jul 07
Aug 08
Sep 09
Oct 10
Nov 11
Dec 12

In [14]:
df_base= pd.read_csv( myout + "/basereg.csv" )

# df_base['yrmo'] = pd.to_datetime( df_base['nwdate'],  format='%b-%d')
# This solution does not work since it will convert Apr-01 to 1900-04-01, which is completely wrong.

df_base[[ 'mon', 'yr']]= df_base['nwdate'].str.split( '-', expand=True )

for i in my_2_col:
    print( "---------2-B-1 Freq Table of {} ---\n".format(i), df_base[i].value_counts() )

# Create the new column
df_base['month'] = df_base['mon'].map(month_dic)

print( "\n---------2-B-3 Freq Table of month ---\n", df_base.month.value_counts() )

df_base['yrmo'] = '20' + df_base[ 'yr'] + df_base['month']

print( "\n---------2-B-4 Freq Table of yrmo ---\n", df_base.yrmo.value_counts() )

# print( "---------2-B-5 Freq Table of nwdate ---\n", df_base.nwdate.value_counts() )

print( "\n---------2-B-6 Freq Table of nwdate /yrmo ---\n", df_base.groupby( ['nwdate', 'yrmo'] ).size() )

df_base= df_base.drop( columns = ['mon', 'yr' , 'month'])

df_base.info()

---------2-B-1 Freq Table of mon ---
 mon
Jan    19
Feb    19
Mar    19
Apr    18
May    18
Jun    18
Jul    18
Aug    18
Sep    18
Oct    18
Nov    18
Dec    18
Name: count, dtype: int64
---------2-B-1 Freq Table of yr ---
 yr
01    12
02    12
03    12
04    12
05    12
06    12
07    12
08    12
09    12
10    12
11    12
12    12
13    12
14    12
15    12
16    12
17    12
18    12
19     3
Name: count, dtype: int64

---------2-B-3 Freq Table of month ---
 month
01    19
02    19
03    19
04    18
05    18
06    18
07    18
08    18
09    18
10    18
11    18
12    18
Name: count, dtype: int64

---------2-B-4 Freq Table of yrmo ---
 yrmo
200101    1
200102    1
200103    1
200104    1
200105    1
         ..
201811    1
201812    1
201901    1
201902    1
201903    1
Name: count, Length: 219, dtype: int64

---------2-B-6 Freq Table of nwdate /yrmo ---
 nwdate  yrmo
Apr-01  200104    1
Apr-02  200204    1
Apr-03  200304    1
Apr-04  200404    1
Apr-05  200504    1
                 ..
Sep-14  201409    1
Sep-15  201509    1
Sep-16  201609    1
Sep-17  201709    1
Sep-18  201809    1
Length: 219, dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 219 entries, 0 to 218
Data columns (total 29 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   nwdate                            219 non-null    object
 1   delta_Unemployment1               218 non-null    float64
 2   delta_Mortgage_rate1              218 non-null    float64
 3   delta_House_Price_Index__Level1   218 non-null    float64
 4   delta_Unemployment3               216 non-null    float64
 5   delta_Mortgage_rate3              216 non-null    float64
 6   delta_House_Price_Index__Level3   216 non-null    float64
 7   delta_Unemployment6               213 non-null    float64
 8   delta_Mortgage_rate6              213 non-null    float64
 9   delta_House_Price_Index__Level6   213 non-null    float64
 10  delta_Unemployment9               210 non-null    float64
 11  delta_Mortgage_rate9              210 non-null    float64
 12  delta_House_Price_Index__Level9   210 non-null    float64
 13  delta_Unemployment12              207 non-null    float64
 14  delta_Mortgage_rate12             207 non-null    float64
 15  delta_House_Price_Index__Level12  207 non-null    float64
 16  delta_Unemployment15              204 non-null    float64
 17  delta_Mortgage_rate15             204 non-null    float64
 18  delta_House_Price_Index__Level15  204 non-null    float64
 19  delta_Unemployment18              201 non-null    float64
 20  delta_Mortgage_rate18             201 non-null    float64
 21  delta_House_Price_Index__Level18  201 non-null    float64
 22  delta_Unemployment21              198 non-null    float64
 23  delta_Mortgage_rate21             198 non-null    float64
 24  delta_House_Price_Index__Level21  198 non-null    float64
 25  delta_Unemployment24              195 non-null    float64
 26  delta_Mortgage_rate24             195 non-null    float64
 27  delta_House_Price_Index__Level24  195 non-null    float64
 28  yrmo                              219 non-null    object
dtypes: float64(27), object(2)
memory usage: 49.7+ KB

In [15]:
df_base_1= df_base[['yrmo', 'delta_Unemployment1', 'delta_Mortgage_rate1', 'delta_House_Price_Index__Level1',
                            'delta_Unemployment3', 'delta_Mortgage_rate3', 'delta_House_Price_Index__Level3',
                            'delta_Unemployment6', 'delta_Mortgage_rate6', 'delta_House_Price_Index__Level6',
                            'delta_Unemployment12', 'delta_Mortgage_rate12', 'delta_House_Price_Index__Level12',
                            'delta_Unemployment24', 'delta_Mortgage_rate24', 'delta_House_Price_Index__Level24'   ]]

df_base_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 219 entries, 0 to 218
Data columns (total 16 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   yrmo                              219 non-null    object
 1   delta_Unemployment1               218 non-null    float64
 2   delta_Mortgage_rate1              218 non-null    float64
 3   delta_House_Price_Index__Level1   218 non-null    float64
 4   delta_Unemployment3               216 non-null    float64
 5   delta_Mortgage_rate3              216 non-null    float64
 6   delta_House_Price_Index__Level3   216 non-null    float64
 7   delta_Unemployment6               213 non-null    float64
 8   delta_Mortgage_rate6              213 non-null    float64
 9   delta_House_Price_Index__Level6   213 non-null    float64
 10  delta_Unemployment12              207 non-null    float64
 11  delta_Mortgage_rate12             207 non-null    float64
 12  delta_House_Price_Index__Level12  207 non-null    float64
 13  delta_Unemployment24              195 non-null    float64
 14  delta_Mortgage_rate24             195 non-null    float64
 15  delta_House_Price_Index__Level24  195 non-null    float64
dtypes: float64(15), object(1)
memory usage: 27.5+ KB

In [16]:
df_base_1.head(30)

,yrmo,delta_Unemployment1,delta_Mortgage_rate1,delta_House_Price_Index__Level1,delta_Unemployment3,delta_Mortgage_rate3,delta_House_Price_Index__Level3,delta_Unemployment6,delta_Mortgage_rate6,delta_House_Price_Index__Level6,delta_Unemployment12,delta_Mortgage_rate12,delta_House_Price_Index__Level12,delta_Unemployment24,delta_Mortgage_rate24,delta_House_Price_Index__Level24
0,200101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,200102,0.028995,0.021646,0.004334,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,200103,0.017408,0.011556,0.004962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,200104,0.012061,0.003717,0.005664,0.058464,0.036919,0.014961,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,200105,0.011569,-0.002900,0.006107,0.041038,0.012373,0.016733,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,200106,0.016465,-0.007681,0.006436,0.040095,-0.006864,0.018206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,200107,0.026463,-0.010763,0.006661,0.054497,-0.021344,0.019204,0.112961,0.015575,0.034164,NaN,NaN,NaN,NaN,NaN,NaN
7,200108,0.041389,-0.012238,0.006892,0.084317,-0.030682,0.019989,0.125355,-0.018309,0.036722,NaN,NaN,NaN,NaN,NaN,NaN
8,200109,0.053861,-0.011122,0.006770,0.121713,-0.034123,0.020324,0.161808,-0.040987,0.038530,NaN,NaN,NaN,NaN,NaN,NaN
9,200110,0.053841,-0.006900,0.006549,0.149091,-0.030260,0.020212,0.203588,-0.051604,0.039415,NaN,NaN,NaN,NaN,NaN,NaN
10,200111,0.039730,0.000855,0.006106,0.147433,-0.017167,0.019425,0.231750,-0.047849,0.039414,NaN,NaN,NaN,NaN,NaN,NaN
11,200112,0.018297,0.010049,0.005658,0.111869,0.004004,0.018313,0.233582,-0.030119,0.038637,NaN,NaN,NaN,NaN,NaN,NaN
12,200201,0.005014,0.014219,0.005979,0.063041,0.025123,0.017743,0.212133,-0.005136,0.037955,0.325094,0.010438,0.072119,NaN,NaN,NaN
13,200202,0.003424,0.010668,0.006707,0.026735,0.034937,0.018344,0.174168,0.017770,0.037770,0.299523,-0.000539,0.074492,NaN,NaN,NaN
14,200203,0.009350,0.002378,0.008199,0.017788,0.027266,0.020885,0.129657,0.031270,0.039199,0.291465,-0.009716,0.077729,NaN,NaN,NaN
15,200204,0.010851,-0.008511,0.009477,0.023625,0.004536,0.024384,0.086667,0.029659,0.042127,0.290255,-0.021945,0.081542,NaN,NaN,NaN
16,200205,0.003254,-0.021738,0.009661,0.023455,-0.027871,0.027337,0.050190,0.007066,0.045682,0.281940,-0.040783,0.085096,NaN,NaN,NaN
17,200206,-0.008922,-0.034541,0.009160,0.005183,-0.064790,0.028298,0.022971,-0.037524,0.049183,0.256553,-0.067643,0.087820,NaN,NaN,NaN
18,200207,-0.013135,-0.038592,0.008444,-0.018803,-0.094870,0.027265,0.004822,-0.090335,0.051648,0.216955,-0.095471,0.089603,NaN,NaN,NaN
19,200208,-0.004672,-0.029891,0.007799,-0.026729,-0.103024,0.025403,-0.003274,-0.130895,0.052741,0.170894,-0.113124,0.090510,NaN,NaN,NaN
20,200209,0.011484,-0.010813,0.006958,-0.006323,-0.079296,0.023202,-0.001140,-0.144086,0.051499,0.128517,-0.112816,0.090698,NaN,NaN,NaN
21,200210,0.019052,0.001638,0.006612,0.025864,-0.039066,0.021370,0.007061,-0.133936,0.048634,0.093728,-0.104277,0.090761,NaN,NaN,NaN
22,200211,0.013689,0.002474,0.006720,0.044225,-0.006700,0.020290,0.017496,-0.109724,0.045693,0.067686,-0.102658,0.091375,NaN,NaN,NaN
23,200212,0.000540,-0.006038,0.007108,0.033281,-0.001926,0.020440,0.026958,-0.081222,0.043642,0.049929,-0.118746,0.092825,NaN,NaN,NaN
24,200301,-0.006334,-0.017358,0.007394,0.007895,-0.020922,0.021222,0.033759,-0.059988,0.042592,0.038582,-0.150322,0.094240,0.363676,-0.139884,0.166359
25,200302,-0.002287,-0.027452,0.006847,-0.008081,-0.050848,0.021350,0.036145,-0.057548,0.041640,0.032870,-0.188443,0.094380,0.332394,-0.188982,0.168872
26,200303,0.008355,-0.035557,0.006508,-0.000266,-0.080366,0.020749,0.033015,-0.082292,0.041189,0.031876,-0.226378,0.092689,0.323341,-0.236094,0.170417
27,200304,0.015550,-0.030178,0.006821,0.021618,-0.093186,0.020176,0.029514,-0.114108,0.041398,0.036575,-0.248044,0.090032,0.326830,-0.269989,0.171574
28,200305,0.015147,-0.002390,0.007558,0.039052,-0.068124,0.020886,0.030972,-0.118971,0.042236,0.048468,-0.228696,0.087929,0.330408,-0.269478,0.173026
29,200306,0.008800,0.035332,0.008726,0.039497,0.002765,0.023105,0.039231,-0.077602,0.043854,0.066189,-0.158823,0.087496,0.322742,-0.226466,0.175316

In [17]:
df_base_1

,yrmo,delta_Unemployment1,delta_Mortgage_rate1,delta_House_Price_Index__Level1,delta_Unemployment3,delta_Mortgage_rate3,delta_House_Price_Index__Level3,delta_Unemployment6,delta_Mortgage_rate6,delta_House_Price_Index__Level6,delta_Unemployment12,delta_Mortgage_rate12,delta_House_Price_Index__Level12,delta_Unemployment24,delta_Mortgage_rate24,delta_House_Price_Index__Level24
0,200101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,200102,0.028995,0.021646,0.004334,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,200103,0.017408,0.011556,0.004962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,200104,0.012061,0.003717,0.005664,0.058464,0.036919,0.014961,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,200105,0.011569,-0.002900,0.006107,0.041038,0.012373,0.016733,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214,201811,0.010217,0.005123,0.002582,0.024323,0.018911,0.007591,0.019929,0.038212,0.014713,0.043000,0.098310,0.030383,0.023563,0.199771,0.054978
215,201812,0.007785,0.003071,0.002585,0.027275,0.014711,0.007709,0.027352,0.036093,0.014924,0.052921,0.088343,0.030535,0.033761,0.192546,0.055390
216,201901,0.002064,0.000374,0.002593,0.020067,0.008569,0.007759,0.032847,0.029814,0.015181,0.057816,0.072141,0.030339,0.035015,0.186587,0.055820
217,201902,-0.006585,-0.002819,0.002401,0.003264,0.000626,0.007579,0.027587,0.019537,0.015169,0.049845,0.055586,0.030008,0.025741,0.179897,0.056189
218,201903,-0.018530,-0.006652,0.002302,-0.023051,-0.009097,0.007296,0.004224,0.005614,0.015006,0.023267,0.040593,0.029669,0.004012,0.169698,0.056464

# Step 3: Combine two types of input files together

In [18]:
df_simu_1= pd.merge(df_simu, df_base_1, on='yrmo', how='inner', indicator='flag_merge')

print ( df_simu_1.flag_merge.value_counts() )

print(pd.crosstab(index= df_simu_1['yrmo'], columns=df_simu_1['product_type'] ) )

flag_merge
both          245000
left_only          0
right_only         0
Name: count, dtype: int64
product_type  Auto  Card  HELOC  Mortgage
yrmo
201401        1283  1280    466      1971
201402        1283  1280    466      1971
201403        1283  1280    466      1971
201404        1283  1280    466      1971
201405        1283  1280    466      1971
201406        1283  1280    466      1971
201407        1283  1280    466      1971
201408        1283  1280    466      1971
201409        1283  1280    466      1971
201410        1283  1280    466      1971
201411        1283  1280    466      1971
201412        1283  1280    466      1971
201501        1283  1280    466      1971
201502        1283  1280    466      1971
201503        1283  1280    466      1971
201504        1283  1280    466      1971
201505        1283  1280    466      1971
201506        1283  1280    466      1971
201507        1283  1280    466      1971
201508        1283  1280    466      1971
201509        1283  1280    466      1971
201510        1283  1280    466      1971
201511        1283  1280    466      1971
201512        1283  1280    466      1971
201601        1283  1280    466      1971
201602        1283  1280    466      1971
201603        1283  1280    466      1971
201604        1283  1280    466      1971
201605        1283  1280    466      1971
201606        1283  1280    466      1971
201607        1283  1280    466      1971
201608        1283  1280    466      1971
201609        1283  1280    466      1971
201610        1283  1280    466      1971
201611        1283  1280    466      1971
201612        1283  1280    466      1971
201701        1283  1280    466      1971
201702        1283  1280    466      1971
201703        1283  1280    466      1971
201704        1283  1280    466      1971
201705        1283  1280    466      1971
201706        1283  1280    466      1971
201707        1283  1280    466      1971
201708        1283  1280    466      1971
201709        1283  1280    466      1971
201710        1283  1280    466      1971
201711        1283  1280    466      1971
201712        1283  1280    466      1971
201801        1283  1280    466      1971

# Step 4: Select Mortgage and HELOC for study

In [19]:
df_mortgage = df_simu_1.loc[ df_simu_1['product_type'].isin( ['Mortgage', 'HELOC'] )  ]

print( df_mortgage['product_type'].value_counts() )

# Mortgage    49441
# Auto        31605
# Card        30460
# HELOC       11368

df_mortgage.info()

product_type
Mortgage    96579
HELOC       22834
Name: count, dtype: int64
<class 'pandas.core.frame.DataFrame'>
Index: 119413 entries, 0 to 244999
Data columns (total 43 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   loan_id                           119413 non-null  int64
 1   origination_date                  119413 non-null  object
 2   report_date                       119413 non-null  object
 3   num_payments                      119413 non-null  int64
 4   original_balance                  119413 non-null  float64
 5   current_balance_bk                119413 non-null  float64
 6   EAD                               119413 non-null  float64
 7   credit_score_orig                 119413 non-null  float64
 8   loan_to_value_orig                119413 non-null  float64
 9   interest_rate                     119413 non-null  float64
 10  product_type                      119413 non-null  object
 11  ever_defaulted                    119413 non-null  bool
 12  default_date                      83349 non-null   object
 13  PD                                119413 non-null  float64
 14  LGD                               119413 non-null  float64
 15  projected_loss                    119413 non-null  float64
 16  loan_term_months                  119413 non-null  int64
 17  unemployment                      119413 non-null  float64
 18  gdp_growth_qoq                    119413 non-null  float64
 19  hpi_change                        119413 non-null  float64
 20  bbb_spread                        119413 non-null  float64
 21  months_elapsed                    119413 non-null  int64
 22  current_balance                   119413 non-null  float64
 23  yrmo                              119413 non-null  object
 24  report_yrmo                       119413 non-null  object
 25  default_yrmo                      83349 non-null   object
 26  flag_default                      119413 non-null  int64
 27  delta_Unemployment1               119413 non-null  float64
 28  delta_Mortgage_rate1              119413 non-null  float64
 29  delta_House_Price_Index__Level1   119413 non-null  float64
 30  delta_Unemployment3               119413 non-null  float64
 31  delta_Mortgage_rate3              119413 non-null  float64
 32  delta_House_Price_Index__Level3   119413 non-null  float64
 33  delta_Unemployment6               119413 non-null  float64
 34  delta_Mortgage_rate6              119413 non-null  float64
 35  delta_House_Price_Index__Level6   119413 non-null  float64
 36  delta_Unemployment12              119413 non-null  float64
 37  delta_Mortgage_rate12             119413 non-null  float64
 38  delta_House_Price_Index__Level12  119413 non-null  float64
 39  delta_Unemployment24              119413 non-null  float64
 40  delta_Mortgage_rate24             119413 non-null  float64
 41  delta_House_Price_Index__Level24  119413 non-null  float64
 42  flag_merge                        119413 non-null  category
dtypes: bool(1), category(1), float64(29), int64(5), object(7)
memory usage: 38.5+ MB

In [20]:
df_mortgage.default_date.value_counts()

default_date
2014-04-30    3724
2014-03-31    3626
2014-05-31    3626
2014-02-28    3136
2014-08-31    3136
2014-07-31    3087
2014-09-30    2989
2014-06-30    2989
2014-11-30    2744
2015-01-31    2744
2015-07-31    2548
2014-12-31    2499
2015-05-31    2499
2014-10-31    2450
2015-03-31    2303
2015-04-30    2254
2015-02-28    2205
2015-06-30    1813
2015-09-30    1764
2016-01-31    1568
2015-12-31    1568
2017-03-31    1568
2015-08-31    1519
2015-11-30    1470
2016-06-30    1274
2016-08-31    1274
2016-02-29    1274
2016-05-31    1274
2017-01-31    1225
2015-10-31    1225
2016-10-31    1176
2017-11-30    1127
2016-07-31    1078
2016-04-30    1078
2017-08-31    1078
2016-12-31    1029
2017-07-31     980
2016-09-30     980
2017-02-28     931
2017-09-30     882
2016-03-31     882
2017-04-30     882
2016-11-30     784
2017-10-31     784
2017-06-30     735
2017-12-31     637
2017-05-31     637
2018-01-31     294
Name: count, dtype: int64

In [21]:
df_mortgage.to_csv( myout + "/CCAR_Mortgage_data_for_model_DEV_20260319_01.csv" )

df_qc= pd.read_csv( myout + "/CCAR_Mortgage_data_for_model_DEV_20260319_01.csv" )

df_qc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119413 entries, 0 to 119412
Data columns (total 44 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Unnamed: 0                        119413 non-null  int64
 1   loan_id                           119413 non-null  int64
 2   origination_date                  119413 non-null  object
 3   report_date                       119413 non-null  object
 4   num_payments                      119413 non-null  int64
 5   original_balance                  119413 non-null  float64
 6   current_balance_bk                119413 non-null  float64
 7   EAD                               119413 non-null  float64
 8   credit_score_orig                 119413 non-null  float64
 9   loan_to_value_orig                119413 non-null  float64
 10  interest_rate                     119413 non-null  float64
 11  product_type                      119413 non-null  object
 12  ever_defaulted                    119413 non-null  bool
 13  default_date                      83349 non-null   object
 14  PD                                119413 non-null  float64
 15  LGD                               119413 non-null  float64
 16  projected_loss                    119413 non-null  float64
 17  loan_term_months                  119413 non-null  int64
 18  unemployment                      119413 non-null  float64
 19  gdp_growth_qoq                    119413 non-null  float64
 20  hpi_change                        119413 non-null  float64
 21  bbb_spread                        119413 non-null  float64
 22  months_elapsed                    119413 non-null  int64
 23  current_balance                   119413 non-null  float64
 24  yrmo                              119413 non-null  int64
 25  report_yrmo                       119413 non-null  int64
 26  default_yrmo                      83349 non-null   float64
 27  flag_default                      119413 non-null  int64
 28  delta_Unemployment1               119413 non-null  float64
 29  delta_Mortgage_rate1              119413 non-null  float64
 30  delta_House_Price_Index__Level1   119413 non-null  float64
 31  delta_Unemployment3               119413 non-null  float64
 32  delta_Mortgage_rate3              119413 non-null  float64
 33  delta_House_Price_Index__Level3   119413 non-null  float64
 34  delta_Unemployment6               119413 non-null  float64
 35  delta_Mortgage_rate6              119413 non-null  float64
 36  delta_House_Price_Index__Level6   119413 non-null  float64
 37  delta_Unemployment12              119413 non-null  float64
 38  delta_Mortgage_rate12             119413 non-null  float64
 39  delta_House_Price_Index__Level12  119413 non-null  float64
 40  delta_Unemployment24              119413 non-null  float64
 41  delta_Mortgage_rate24             119413 non-null  float64
 42  delta_House_Price_Index__Level24  119413 non-null  float64
 43  flag_merge                        119413 non-null  object
dtypes: bool(1), float64(30), int64(8), object(5)
memory usage: 39.3+ MB

In [22]:
from datetime import datetime
end = datetime.now(ZoneInfo("America/New_York"))
duration = end - start

print(f"Started:  {start}")
print(f"Finished: {end}")
print(f"\nDuration: {duration}")                    # 0:00:02.351234
print(f"Duration: {duration.total_seconds():.3f} seconds")

Started:  2026-03-19 20:08:18.167467-04:00
Finished: 2026-03-19 20:08:32.685611-04:00

Duration: 0:00:14.518144
Duration: 14.518 seconds